format = '''
$directory$git_branch$git_status$git_commit$kubernetes$aws$cmd_duration
$character'''

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '

[aws]
symbol = "  "
style = "#ff9900"
format = '[$symbol($profile )(\[$duration\] )]($style)'

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "#f64d27"
symbol = " "

[golang]
format = '[$symbol($version )]($style)'
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[cmd_duration]
disabled = false

[kubernetes]
format ='[$symbol$context( \($namespace\))]($style) '
symbol = "⎈ "
style = "#316ce6"
disabled = false
[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:ap-northeast-1:615953452051:cluster/service-staging"
context_alias = "service-staging"
[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:ap-northeast-1:615953452051:cluster/service-production"
style = "red"
context_alias = "service-production"
